server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Toutes les routes React redirigent vers index.html (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optimisation du cache pour les fichiers statiques (CSS, JS, Images)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
