# ==============================================================================
#  Configuration commune à TOUS les profils (dev, test, prod)
# ==============================================================================

spring:
  application:
    name: backend

  # === JPA / Hibernate (commun) ===
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  # === Jackson ===
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

# === Server ===
server:
  port: 8080

# === Actuator (monitoring) ===
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
